document.write('<div align=center style=\"margin-right: 20\">')
document.write('<a href=\"nov99ed.htm\">Letter From<br>The Editor</a><br><br>')
document.write('<a href=\"nov99rv.htm\">DRAGONreviews</A>')
document.write('</div><img src=\"images/mid.gif\"><div align=center style=\"margin-right: 20\">')
document.write(storlist[25] + '<br><br>')
document.write(storlist[26] + '<br><br>')
document.write(storlist[28] + '<br><br>')
document.write(storlist[29] + '<br><br>')
document.write(storlist[27])
document.write('</div><img src=\"images/mid.gif\"><div align=center style=\"margin-right: 20\">')
document.write('<a href=\"archives.htm\">-Past Issues-</a><br><br></div>')